name: Build and push to another repo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build:doc

      - name: Clone destination repository
        run: |
          git clone https://aMaoHongmei:${{ secrets.API_TOKEN_GITHUB }}@github.com/aMaoHongmei/fe-toolkit-doc.git destination_repo

      - name: Backup all files in the repository
        run: |
         mkdir backup
         cp -r destination_repo/* backup/

      - name: Remove all files from the repository
        run: |
          cd destination_repo
          git rm -r *

      - name: Commit and push changes
        run: |
          cd destination_repo
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name "aMaoHongmei"
          git commit -m "Remove all files"
          git push origin master

      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username:  'aMaoHongmei'
          destination-repository-name: 'fe-toolkit-doc'
          user-email: ${{ secrets.USER_EMAIL }}
          target-branch: master
